version: '3.8'

services:
  pg:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: mem
      POSTGRES_PASSWORD: mem
      POSTGRES_DB: mem
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped