version: '3.8'

services:
  sage-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: sage-mcp-single:minimal
    container_name: sage-mcp
    restart: unless-stopped
    stdin_open: true
    tty: false
    ports:
      # PostgreSQL端口映射（仅开发调试时启用）
      # 生产环境建议注释以下行以提高安全性
      - "${DB_MAPPED_PORT:-5432}:5432"  # PostgreSQL调试端口
    environment:
      # 基础配置
      - SAGE_ENV=${SAGE_ENV:-production}
      - SAGE_LOG_LEVEL=${SAGE_LOG_LEVEL:-INFO}
      - SAGE_LOG_DIR=${SAGE_LOG_DIR:-/var/log/sage}
      - SAGE_MAX_RESULTS=${SAGE_MAX_RESULTS:-10}
      
      # 数据库配置
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-sage_memory}
      - DB_USER=${DB_USER:-sage}
      - DB_PASSWORD=${DB_PASSWORD:-sage123}
      - DATABASE_URL=postgresql://${DB_USER:-sage}:${DB_PASSWORD:-sage123}@${DB_HOST:-localhost}:${DB_PORT:-5432}/${DB_NAME:-sage_memory}
      
      # PostgreSQL 容器配置
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sage123}
      
      # 向量化服务配置
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      
      # MCP 服务配置
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-sage}
      - MCP_PROTOCOL_VERSION=${MCP_PROTOCOL_VERSION:-2024-11-05}
    volumes:
      # 挂载本地代码，方便开发调试
      - ./sage_core:/app/sage_core
      - ./sage_mcp_stdio_single.py:/app/sage_mcp_stdio_single.py
      # 数据持久化策略
      - sage-data:/var/lib/postgresql/data
      - sage-logs:/var/log/sage
      - sage-supervisor-logs:/var/log/supervisor
      # 配置文件通过环境变量传递，避免挂载权限问题
      # - ./config:/app/config:ro
      # 备份目录映射
      - ./backups:/app/backups
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sage-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgresql
  sage-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/logs/sage
  sage-supervisor-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/logs/supervisor