services:
  pg:
    image: pgvector/pgvector:pg16
    container_name: sage-postgres
    environment:
      POSTGRES_USER: mem
      POSTGRES_PASSWORD: mem
      POSTGRES_DB: mem
    ports:
      - "5432:5432"
    volumes:
      - sage_pgdata:/var/lib/postgresql/data
      - ./init-pgvector.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mem -d mem"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  sage-mcp:
    build:
      context: .
      dockerfile: Dockerfile.final
    container_name: sage-mcp-server
    environment:
      DATABASE_URL: postgresql://mem:mem@pg:5432/mem
      SILICONFLOW_API_KEY: ${SILICONFLOW_API_KEY}
      DB_HOST: pg
      DB_PORT: 5432
      DB_NAME: mem
      DB_USER: mem
      DB_PASSWORD: mem
    ports:
      - "17800:17800"
    depends_on:
      pg:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:17800/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  sage_pgdata:
    driver: local

networks:
  default:
    name: sage-network
