version: "3.9"
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: sage-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sage
      POSTGRES_PASSWORD: sage123
      POSTGRES_DB: sage_memory
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - sage-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sage"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  sage-net:
    driver: bridge