version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: pgvector/pgvector:pg16
    container_name: sage-postgres
    environment:
      POSTGRES_DB: sage_memory
      POSTGRES_USER: sage
      POSTGRES_PASSWORD: sage123
    volumes:
      - sage-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sage"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Sage STDIO 服务器
  sage-stdio:
    build: .
    container_name: sage-stdio
    command: python sage_mcp_stdio_v3.py
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sage_memory
      DB_USER: sage
      DB_PASSWORD: sage123
      EMBEDDING_MODEL: Qwen/Qwen3-Embedding-8B
      EMBEDDING_DEVICE: cpu
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    stdin_open: true
    tty: true

  # Sage HTTP/SSE 服务器
  sage-http:
    build: .
    container_name: sage-http
    command: python sage_mcp_http_sse.py
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sage_memory
      DB_USER: sage
      DB_PASSWORD: sage123
      EMBEDDING_MODEL: Qwen/Qwen3-Embedding-8B
      EMBEDDING_DEVICE: cpu
      PORT: 17801
      HOST: 0.0.0.0
      REQUIRE_AUTH: "false"
      OAUTH_CLIENT_ID: sage-mcp-client
      OAUTH_CLIENT_SECRET: sage-secret-123
      JWT_SECRET: sage-jwt-secret-456
    ports:
      - "17801:17801"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:17801/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 旧版 HTTP 服务器（兼容性）
  sage-http-legacy:
    build: .
    container_name: sage-http-legacy
    command: python app/sage_mcp_server.py
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sage_memory
      DB_USER: sage
      DB_PASSWORD: sage123
      EMBEDDING_MODEL: Qwen/Qwen3-Embedding-8B
      EMBEDDING_DEVICE: cpu
      PORT: 17800
      HOST: 0.0.0.0
    ports:
      - "17800:17800"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs

volumes:
  sage-postgres-data:
    name: sage-postgres-data

networks:
  default:
    name: sage-network